apiVersion: v1
data:
  secret-access-key: Q09xSlIrQU9HOWRUVVRJTmswOVduRTh0dlZTeEtKc29zbmJDaHpENQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
