apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: wildcard-letsencrypt-prod
    # Add a single challenge solver, DNS01
    solvers:
    # this solver handles example.org challenges
    # and uses explicit credentials
    - selector:
        dnsZones:
          - "iojas.me"
          - "*.iojas.me"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z02946051UL3RRPROSJSL
          accessKeyID: AKIA455S4Q57ZLIT4KOX
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key